- id: dmeta-clear-metadata
  name: DMeta
  description: Use `dmeta` to clear metadata from Microsoft Office files
  entry: python -m dmeta --clear-all --inplace
  language: python
  types: [file]
  files: \.(docx|pptx|xlsx)$
  pass_filenames: true
  stages: [commit]
  
