- id: dmeta-clear-metadata
  name: DMeta
  description: Use `dmeta` to clear metadata from Microsoft Office files
  entry: dmeta --clear-all --inplace
  language: python
  types: [file]
  files: \.(docx|pptx|xlsx)$
