{% set name = "DMeta" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/dmeta
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.6
    run:
        - art >=1.8
        - python >=3.6
about:
    home: https://github.com/openscilab/dmeta
    license: MIT
    license_family: MIT
    summary: Python library for machine learning input and output
    description: |
        DMeta is an open source Python package that removes metadata of microsoft office files.
        
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/dmeta
extra:
    recipe-maintainers:
        - AHReccese
