blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/626twyuPZG
    about: Ask questions and discuss with other DMeta community members 
  - name: Website
    url: https://openscilab.com/
    about: Check out our website for more information
